#!/bin/sh
echo -e 'HTTP/1.1 200 OK\r\nContent-type: text/html\r\n\r\n'

echo "<html><head><title>Last accesses</title></head><body><h1>Last accesses:</h1><table width=70% border=1 align=center><thead><tr><th><p>ID</p></th><th><p>Name</p></th><th><p>Date/Time</p></th><th><p>Alowed</p></th><th><p>Picture</p></th></tr></thead><tbody>"

exec /root/labmic/log_parser

echo "</tbody></table></body></html>"
